### ISSUE TITLE
Diphthongs characters not plotting correctly?

### ISSUE THREAD

**Issue by jmriebold** [drammock/phonR#32]
When plotting diphthong means, characters are plotted at all timepoints (except the last if `diph.arrows = T`). Perhaps I'm not using the right parameter though?

Edit: works correctly for tokens, just not for means.

Edit 2: Just noticed that although my `pch.means` is vowel + environment (using `paste()`) that only gets plotted at timepoint 1. The other timepoints get labeled with the vowel alone.

**Comment by drammock** [comment]
correction: I had apparently already implemented the "plot first timepoint only" function, but not fully tested it, so what's happening is that, when `diph.arrows=TRUE`, it plots each timepoint with the first character of the vowel as a `pch` via a call to `points(...)`, and then *also* plots the first timepoint with the full environment via a call to `text(...)`. This is indeed not the intended behavior; I just didn't see it because I hadn't yet written the test case when `diph.arrows=TRUE`.
