### ISSUE TITLE
Polygon line drawn through character when plotting tokens

### ISSUE THREAD

**Issue by jmriebold** [drammock/phonR#38]
When drawing a polygon, the polygon line stops on either side of the character when plotting means, but when plotting tokens it goes through the character, making it more difficult to read. See examples below.

# Plotting means

<code>plotVowels(f1 = dialect_data.region$F1, f2 = dialect_data.region$F2, vowel = dialect_data.region$Vowel, group = dialect_data.region$Region, var.col.by = dialect_data.region$Region, col = c("firebrick2", "blueviolet"), **plot.tokens = F, plot.means = T, pch.means = dialect_data.region$Vowel**, cex.means = 1.25, cex.lab = 2, xlim = f2_lim, ylim = f1_lim, poly.line = T, poly.order = c("i", "\U026A", "e", "\U025B", "æ", "\U0251", "\U0254", "o", "\U028A", "u"), pretty = T, main = levels(dialect_data$Region)[i], cex.main = 2.5, font.main = 1.5, xlab = "F2 (Hz)", ylab = "F1 (Hz)", legend.kwd = "bottomright", legend.args = c(lwd = 2))</code>

![means](https://cloud.githubusercontent.com/assets/6983392/7899026/b3e6218e-06c8-11e5-8470-98db4e33492c.png)

# Plotting tokens

<code>plotVowels(f1 = dialect_data.region$F1, f2 = dialect_data.region$F2, vowel = dialect_data.region$Vowel, group = dialect_data.region$Region, var.col.by = dialect_data.region$Region, col = c("firebrick2", "blueviolet"), **plot.tokens = T, pch.tokens = dialect_data.region$Vowel**, cex.tokens = 1.25, cex.lab = 2, xlim = f2_lim, ylim = f1_lim, poly.line = T, poly.order = c("i", "\U026A", "e", "\U025B", "æ", "\U0251", "\U0254", "o", "\U028A", "u"), pretty = T, main = levels(dialect_data$Region)[i], cex.main = 2.5, font.main = 1.5, xlab = "F2 (Hz)", ylab = "F1 (Hz)", legend.kwd = "bottomright", legend.args = c(lwd = 2))</code>

![tokens](https://cloud.githubusercontent.com/assets/6983392/7899029/cbeaf340-06c8-11e5-9ed2-96e4d531a34f.png)

**Comment by drammock** [comment]
This seems like sort of an edge case to me (where you have exactly one token for each vowel).  If I set `type="c"` for cases where `plot.means=FALSE` under more normal circumstances (where there is a cloud of tokens for each vowel, instead of just a single token), then you end up with a gapped line with nothing at its intersections. I'm open to suggestions about what is the best approach, but so far you haven't convinced me that anything should change. 

Here's what I think is an easy work-around for the case where you have only one token per speaker/vowel category:
```r
foo <- indo[indo$subj %in% "M01",]
bar <- indo[indo$subj %in% "F02",]
baz <- rbind(foo[!duplicated(foo$vowel),], bar[!duplicated(bar$vowel),])
with(baz, plotVowels(f1, f2, vowel, group=subj, plot.means=TRUE, plot.tokens=FALSE, poly.line=TRUE, poly.order=c("i", "e", "a", "o", "u"), pch.means=vowel, var.col.by=subj, pretty=TRUE))
```
![rplot001](https://cloud.githubusercontent.com/assets/1810515/7899969/0edffdbc-076e-11e5-8836-0c35f175a032.png)

**Comment by jmriebold** [comment]
Oh, yes of course, you're right. I've never used the polygon option when plotting (actual) tokens and didn't consider that that behavior actually makes plenty of sense when you have a cloud of tokens distributed around a mean. In my case they were actually means (calculated prior to the phonR call), but regardless, if there's only one per vowel/word/whatever the plot.means = T option works just fine.
